package ssafy.d210.backend.enumeration.response;
//
public enum HereStatus {
    SUCCESS_SIGNUP,
    SUCCESS_LOGIN,
    SUCCESS_MYPAGE,
    SUCCESS_ASSETS,
    SUCCESS_OWNLECTURE,
    SUCCESS_FIND_EMAIL,
    SUCCESS_MAKELECTURE,
    SUCCESS_CERTIFICATE,
    SUCCESS_CERTIFICATE_DETAIL,
    SUCCESS_CERTIFICATE_OWN,
    SUCCESS_LOGOUT,
    SUCCESS_REFRESH,
    SUCCESS_REPORT_ALL,
    SUCCESS_REPORT_DETAIL,
    SUCCESS_LECTURE_MAKE,
    SUCCESS_LECTURE,
    SUCCESS_LECTURE_CATEGORY,
    SUCCESS_LECTURE_DETAIL,
    SUCCESS_LECTURE_SAVEPLAYTIME,
    SUCCESS_LECTURE_BUY,
    SUCCESS_QUIZ,
    SUCCESS_QUIZ_SUBMIT,
    SUCCESS_REPORT,
    SUCCESS_LECTURE_SEARCH

}
