server:
  port: ${PORT}
#
spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret: ${JWT_SECRET}

  encryption:
    key: ${AES_256}

  server:
    forward-headers-strategy: NATIVE
    tomcat:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto

springdoc:
  server:
    url: https://j12d210.p.ssafy.io

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
#logging:
#  level:
#    root: DEBUG